'use client';

import React, { useState, useEffect } from 'react';
import { ComprehensiveAnalysisResult } from '@/lib/analysis-service';
import { ColorDrapingData } from '@/lib/color-draping-types';
import { transformToColorDrapingData, validateColorDrapingData, createFallbackColorDrapingData } from '@/lib/color-draping-utils';
import EntryScreen from './entry-screen';
import WalkthroughFlow from './walkthrough-flow';
import SummaryScreen from './summary-screen';

interface ColorDrapingWalkthroughProps {
  analysisResult: ComprehensiveAnalysisResult;
  userPhotoUrl: string;
  analysisId: string;
  onViewFullAnalysis: () => void;
  className?: string;
}

type WalkthroughState = 'entry' | 'walkthrough' | 'summary';

export const ColorDrapingWalkthrough: React.FC<ColorDrapingWalkthroughProps> = ({
  analysisResult,
  userPhotoUrl,
  analysisId,
  onViewFullAnalysis,
  className = ''
}) => {
  const [currentState, setCurrentState] = useState<WalkthroughState>('entry');
  const [drapingData, setDrapingData] = useState<ColorDrapingData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Initialize draping data
  useEffect(() => {
    const initializeDrapingData = async () => {
      try {
        setIsLoading(true);
        setError(null);

        // Transform analysis result to draping data
        const transformedData = transformToColorDrapingData(
          analysisResult,
          userPhotoUrl,
          analysisId
        );

        // Validate the data
        if (!validateColorDrapingData(transformedData)) {
          throw new Error('Invalid draping data');
        }

        setDrapingData(transformedData);
      } catch (err) {
        console.error('Failed to initialize draping data:', err);
        setError('Failed to prepare walkthrough data');
        
        // Use fallback data
        const fallbackData = createFallbackColorDrapingData(analysisId);
        setDrapingData(fallbackData);
      } finally {
        setIsLoading(false);
      }
    };

    if (analysisResult && userPhotoUrl && analysisId) {
      initializeDrapingData();
    }
  }, [analysisResult, userPhotoUrl, analysisId]);

  const handleStartWalkthrough = () => {
    setCurrentState('walkthrough');
  };

  const handleWalkthroughComplete = () => {
    setCurrentState('summary');
  };

  const handleBackToEntry = () => {
    setCurrentState('entry');
  };

  const handleRestartWalkthrough = () => {
    setCurrentState('walkthrough');
  };

  const handleDownloadPalette = async () => {
    if (!drapingData) return;

    try {
      // Create a simple text format for download
      const paletteText = `
Your Color Analysis Results
===========================

Color Season: ${drapingData.colorSeason}

Best Colors:
${drapingData.colors
  .filter(c => c.verdict === 'best')
  .map(c => `• ${c.name} (${c.hex}) - ${c.feedback}`)
  .join('\n')}

Colors to Avoid:
${drapingData.colors
  .filter(c => c.verdict === 'avoid')
  .map(c => `• ${c.name} (${c.hex}) - ${c.feedback}`)
  .join('\n')}

Generated by Color Analysis Tool
      `.trim();

      const blob = new Blob([paletteText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `color-palette-${drapingData.colorSeason.toLowerCase().replace(' ', '-')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Failed to download palette:', err);
      alert('Failed to download palette. Please try again.');
    }
  };

  const handleShareLookbook = async () => {
    if (!drapingData) return;

    try {
      if (navigator.share) {
        await navigator.share({
          title: `My Color Analysis - ${drapingData.colorSeason}`,
          text: `I just discovered I'm a ${drapingData.colorSeason}! Check out my personalized color palette.`,
          url: window.location.href
        });
      } else {
        // Fallback: copy to clipboard
        const shareText = `I just discovered I'm a ${drapingData.colorSeason}! Check out my personalized color palette: ${window.location.href}`;
        await navigator.clipboard.writeText(shareText);
        alert('Share text copied to clipboard!');
      }
    } catch (err) {
      console.error('Failed to share:', err);
      alert('Failed to share. Please try again.');
    }
  };

  if (isLoading) {
    return (
      <div className={`walkthrough-loading ${className}`}>
        <div className="loading-content">
          <div className="loading-spinner">
            <div className="spinner" />
          </div>
          <h2>Preparing Your Color Walkthrough...</h2>
          <p>Setting up your personalized draping experience</p>
        </div>
      </div>
    );
  }

  if (error || !drapingData) {
    return (
      <div className={`walkthrough-error ${className}`}>
        <div className="error-content">
          <h2>Unable to Load Walkthrough</h2>
          <p>{error || 'Something went wrong while preparing your color walkthrough.'}</p>
          <button onClick={onViewFullAnalysis} className="error-button">
            View Full Analysis Instead
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className={`color-draping-walkthrough ${className}`}>
      {currentState === 'entry' && (
        <EntryScreen
          onViewFullAnalysis={onViewFullAnalysis}
          onStartWalkthrough={handleStartWalkthrough}
          analysisComplete={true}
        />
      )}

      {currentState === 'walkthrough' && (
        <WalkthroughFlow
          drapingData={drapingData}
          onComplete={handleWalkthroughComplete}
          onBack={handleBackToEntry}
        />
      )}

      {currentState === 'summary' && (
        <SummaryScreen
          drapingData={drapingData}
          onDownloadPalette={handleDownloadPalette}
          onShareLookbook={handleShareLookbook}
          onRestartWalkthrough={handleRestartWalkthrough}
          onViewFullAnalysis={onViewFullAnalysis}
        />
      )}
    </div>
  );
};

export default ColorDrapingWalkthrough;